apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
spec:
  template: # pod definition (basically a copy paste of the metadata and spec content of the pod.yml)
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  # <- DIFFERENCE with replication controllers
  # replicasets allow to manage also pods that were not created by it
  selector:
    matchLabels:
      type: front-end
