apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template: # pod definition (basically a copy paste of the metadata and spec content of the pod.yml)
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
