apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # the port where the interface (back-end) is exposed
      port: 80       # the port where the svc is exposed
  selector:
    app: myapp
    type: back-end