apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
spec:
- apiGroups: [""] # don't specify for core group
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
  resourceNames: ["blue", "orange"]