apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app.kubernetes.io/name: simple-webapp
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    ports:
      - containerPort: 8080
    livinessProbe: # tests if the running app is healthy
      httpGet: # or tcpSocket or exec
        path: /api/ready
        port: 8080

      initialDelaySeconds: 10 # delay before starting the probe
      periodSeconds: 5 # how many seconds before retrying probe
      failureThreshold: 8 # how many times to probe before pod is considered not ready; default value is 3