apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # run 3 pods or as many pods as necessary for 3 successful completions
  parallelism: 3 # create all 3 pods simultaneously so they don't run one after the other; and if 2 complete at the same time then job attempts to create only one pod until completion
  backoffLimit: 20 # number of attempts to succeed
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ["expr",  "3", "+", "2"]
      restartPolicy: Never
