apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp

spec:
  containers:
  - name: web-app
    image: web-app
    ports:
      - containerPort: 8080
  initContainers: # runs at start and ends once it's done; then main container starts
  - name: db-checker
    image: busybox
    command: ['wait-for-db-to-start.sh']
  - name: api-checker # this is run sequentially, so it's run after the first init container ends
    image: busybox
    command: ['wait-for-api-to-start.sh']