apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      version: v2 # different label value
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2 # different label value
    spec:
      containers:
      - name: myapp-container
        image: myapp-image:1.0
    replicas: 5
