apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      version: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2
        app: front-end # same label
    spec:
      containers:
      - name: myapp-container
        image: myapp-image:2.0 # newer version
    replicas: 1 # set lower number of replicas - with Istio it's possible to set a precise percentage of traffic to be routed
